@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzY5ODU3MDYyLCJleHAiOjE3Njk4NjA2NjIsIm5iZiI6MTc2OTg1NzA2MiwianRpIjoiaEFxTjEzYzUxOFJIZlA1eSIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.HtuAXmacyR9hKeVugOwBa4qzid1JtIrfcvirE4MElJA
@http = http://127.0.0.1:8000/api


### =========================
### LOGIN
### =========================
POST {{http}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "password123"
}


### =========================
### ME
### =========================
GET {{http}}/me
Accept: application/json
Authorization: Bearer {{token}}


### =========================
### CRUD VENDOR ITEM
### =========================

### get all vendor item
GET {{http}}/vendor-items
Accept: application/json
Authorization: Bearer {{token}}


### post vendor item
POST {{http}}/vendor-items
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id_vendor": 1,
  "id_item": 2,
  "harga_sebelum": 20000,
  "harga_sekarang": 17000
}


### get vendor item by id
GET {{http}}/vendor-items/2
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json


### edit vendor item by id
PUT {{http}}/vendor-items/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "harga_sebelum": 17000,
  "harga_sekarang": 16000
}


### delete vendor item by id
DELETE {{http}}/vendor-items/2
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json
